### ISSUE TITLE
Error when building the project

### ISSUE THREAD

**Issue by dmitrvk** [yaroslav4167/RuFix#1]
I can not build the project due to the following error:

`Error:(16, 1) java: Plugin ID 'ruFix' must match pattern '[a-z][a-z0-9-_]{0,63}'. It should be lower case, start with an alphabetic character and may only contain alphanumeric characters, underscores or dashes.`

I tried to change the plugin ID from `ruFix` to `rufix` on line 16 in `RuFix.java`:

```java
@Plugin(id = "rufix", name = "RuFix", version = "1.0", description = "ruFix")
```
The build was successful after that change.

Should I submit the change in PR?

**Comment by yaroslav4167** [comment]
Ok. This is fixed. Thx.
