### ISSUE TITLE
Missing release artifacts

### ISSUE THREAD

**Issue by dmitrvk** [yaroslav4167/RuFix#5]
There was the [release 1.0](https://github.com/yaroslav4167/RuFix/commit/bed97d0ba278c85f4330e2e0c8d9985c5c7c6b2c) recently, however there is nothing in the [Releases](https://github.com/yaroslav4167/RuFix/releases) section. That would be nice to see the `jar` file with plugin available to download.

**Comment by yaroslav4167** [comment]
Published [first release](https://github.com/yaroslav4167/RuFix/releases/tag/1.0)
